### ISSUE TITLE
Pings look funky on minimap

### ISSUE THREAD

**Issue by TheLonelySheep** [amazingalek/terraria-ping#32]
The lines of the sprite are so small, the sprite seems to flicker on the minimap. 
![image](https://user-images.githubusercontent.com/26361108/79635222-034e3a00-8170-11ea-9dd3-9f344d4b74ce.png)

**Comment by amazingalek** [comment]
Thanks for the report, @TheLonelySheep ! It looks fine in my game, so let's start with some questions :)
Can you experiment with game zoom and UI scale, and see if any of them improve the ping graphics?

**Comment by TheLonelySheep** [comment]
I have a 24" 1920x1080 Monitor. Ingame it looks fine (see attached image), but on the minimap or even when you expand it, it looks like that. Playing with UI scale makes things better, but then the UI is so large and crowded, that it makes the game unplayable.

My guess is that there is too little yellow compared to the black border.
![image](https://user-images.githubusercontent.com/26361108/79688649-e8eb8d80-824f-11ea-869f-7bda6348cb11.png)

**Comment by amazingalek** [comment]
Yeah, I see what you mean. I'll try to make this look good on 1080p.

**Comment by amazingalek** [comment]
@TheLonelySheep I improved the ping sprite, tested on 1080p. Let me know if you have any more issues :)
